version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sass
    versions:
    - 1.32.8
  - dependency-name: vue-masonry
    versions:
    - 0.12.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
  - dependency-name: vuetify
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: lodash
    versions:
    - 4.17.20
